### ISSUE TITLE
Invalid username persisted in Auth example

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#124]
In the Authentication example:

1.  place an invalid username/password into the login form
2. Let the sign in operation fail
3. Restart the app,
4. The invalid username is now persisted as it's shown in the "Sign in with [username]" button

**Comment by njarecha** [comment]
@dfeinzimer Please re-test this with latest changes.

**Comment by dfeinzimer** [comment]
This looks fixed, thank you @njarecha!
