### ISSUE TITLE
Readme has wrong package links.

### ISSUE THREAD

**Issue by SpaceTrucker2196** [Esri/arcgis-maps-sdk-swift-toolkit#211]
The readme file has incorrect package names. easy fix.

**Comment by mhdostal** [comment]
Thank you very much for your interest in the Toolkit!  We will be releasing the official initial version on December 14, which will resolve your issue.  This will coincide with the release of Esri's new _ArcGIS Maps SDK for Swift_.

Feel free to take  look at the `v.next` [branch](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/tree/v.next) for a full list of components available in the initial release.

**Comment by SpaceTrucker2196** [comment]
Hey thanks. I’m mainly interested in the import export functions. I work developing guidance system for ag aviation and aerial firefighting and we have a lot of customers who use would like to use exports of our data in arc-gis.

**Comment by dfeinzimer** [comment]
Hi Jeff, the beta for our new Swift SDK and the associated Toolkit (this repo) is available as of today. See [here](https://community.esri.com/t5/arcgis-maps-sdks-native-blog/introducing-the-arcgis-maps-sdk-for-swift-toolkit/ba-p/1241311) for more info. The package should now work correctly as expected.

If you'd like to provide a little more info on the import/export functionality you need, we can point you in the right direction.

We hope you enjoy working with the new SDK!
