### ISSUE TITLE
Resolve new compile warnings

### ISSUE THREAD

**Issue by mhdostal** [Esri/arcgis-maps-sdk-swift-toolkit#214]
![image](https://user-images.githubusercontent.com/3998072/206760900-836d960c-8077-4c6b-9d43-1082e9091a25.png)

Xcode 14.1
iPad Pro 10.5" iOS 16.1

**Comment by philium** [comment]
@mhdostal Do you happen to know why these warnings suddenly started appearing?

**Comment by mhdostal** [comment]
@zach suggested it may be because we're using the binary framework.

**Comment by zkline101** [comment]
@philium The only possible reason I could think of is the warnings showed up to me based on how the Swift API was being digested in the toolkit. If it was a local build I did not see the warnings but if the toolkit was using the binary frameworks the warnings showed up.

**Comment by dfeinzimer** [comment]
Yup I'm seeing the same now when building with binaries. Not sure of the reason for the difference.
