### ISSUE TITLE
Runtime warning using `OverviewMap.map(_:)`

### ISSUE THREAD

**Issue by philium** [Esri/arcgis-maps-sdk-swift-toolkit#225]
The following runtime warning is generated when using `OverviewMap.map(_:)`:

![image](https://user-images.githubusercontent.com/2257493/208494105-e7346c96-d6c6-452a-95c8-4b3fd38fca02.png)

In addition to the warning, the modifier approach isn't great for a couple reasons:

- SwiftUI view content is usually taken via an initializer rather than a modifier. In general, modifiers are used to configure views, not provide data for them.
- It encourages the map to be created where the modifier is used, in the body of a view, which is an anti-pattern. With that naive approach, the map would get created every time the view's body is re-computed.

A better approach might be to have a separate "initializer" (static method it looks like) that takes a map.

**Comment by mhdostal** [comment]
Thanks @philium !
