### ISSUE TITLE
Cannot reselect site using floor filter

### ISSUE THREAD

**Issue by philium** [Esri/arcgis-maps-sdk-swift-toolkit#229]
Steps to reproduce:

1. Open the Floor Filter example
2. Tap/click the button to open the site selector
3. Tap/click on a site
4. Tap/click the back button
5. Tap/click the same site

Expected: The site will be selected and the facilities for that site will be presented.
Actual: Nothing happens.

**Comment by dfeinzimer** [comment]
Resolved by #236
