### ISSUE TITLE
Floor Filter - Two close buttons can appear

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#244]
The Swift Samples app uses the Floor Filter component with data that appears to cause two close buttons to appear.

![Screenshot 2023-01-09 at 11 59 54](https://user-images.githubusercontent.com/16397058/211397225-b23fed03-57fa-49a6-9c91-ecaba4e9aa65.png)

**Comment by philium** [comment]
The problem appears to be that both `FacilitiesList` and its parent (`SitesList`) have a modifier for the close button. It should only be on one of them.
