### ISSUE TITLE
`Bookmarks` - Add binding `selection` init parameter

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#246]
Update:
See discussion below

---

Original: 
As an alternate to using a viewpoint, the bookmarks component can potentially take advantage of the `setBookmark(_:)` method on a map or scene view proxy.

**Comment by philium** [comment]
Alternatively, it could be simplified by taking a binding to the selected bookmark as an initializer parameter, giving the caller flexibility to do whatever they want when the selected bookmark is updated (`onChange(of selectedBookmark) { … }`). I think that would be better than taking a binding to a viewpoint.

**Comment by dfeinzimer** [comment]
Closing; [`onSelectionChanged(perform:)`](https://developers.arcgis.com/swift/toolkit-api-reference/documentation/arcgistoolkit/bookmarks/onselectionchanged(perform:)) is provided

**Comment by philium** [comment]
@dfeinzimer Was there any consideration given to taking a binding to the selection? While there is the modifier that you pointed out, taking a binding to the selected bookmark would be simpler and more idiomatic in SwiftUI. Many SwiftUI-provided modifiers take a selection binding instead of providing a separate modifier to inform when the selection has changed.

**Comment by dfeinzimer** [comment]
Yes - I still think we should do it and I thought we had an issue for it but I'm not seeing it so I'll reopen and re-characterize this issue instead.

**Comment by dfeinzimer** [comment]
Some additional API considerations:

The current initializers are:

`init(isPresented: Binding<Bool>, bookmarks: [Bookmark], viewpoint: Binding<Viewpoint?>?)`
&
`init(isPresented: Binding<Bool>, bookmarks: [Bookmark], viewpoint: Binding<Viewpoint?>?)`

Would we want to add 2 new initializers:
`init(isPresented: Binding<Bool>, bookmarks: [Bookmark], selection: Binding<Bookmark?>?)`
&
`init(isPresented: Binding<Bool>, geoModel: GeoModel, selection: Binding<Bookmark?>?)`

brining us to a total of 4? 4 seems like it would be a lot to me.

**Comment by philium** [comment]
The selection parameter should be non-optional because those initializers should only be used with a selection binding. In my opinion, having four initializers isn't a big deal. Several SwiftUI views have much more than four initializers.
