### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by njarecha** [Esri/arcgis-maps-sdk-swift-toolkit#247]
This [PR](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/243) adds support for localization for toolkit. However, there are more strings needs to moved in the file and get translated later on.

**Comment by dfeinzimer** [comment]
Useful initializers:
 - [`String(localized:comment:)`](https://developer.apple.com/documentation/swift/string/init(localized:table:bundle:locale:comment:))
- [`Text(_:format:)`](https://developer.apple.com/documentation/swiftui/text/init(_:format:))
- [`Int.formatted(_:)`](https://developer.apple.com/documentation/swift/int/formatted(_:)-36hqc)
