### ISSUE TITLE
[Floor Filter] - Allow to adjust default floor filter width and color.

### ISSUE THREAD

**Issue by mansibarodia10057** [Esri/arcgis-maps-sdk-swift-toolkit#258]
Currently minimum [floor filter width](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/main/Sources/ArcGISToolkit/Components/FloorFilter/FloorFilter.swift#L61) is set to 60. Floor filter still looks big when opened on smaller devices. Also since the app supports branding colors set via MDM, where the user can set the theme any other color other than standard blue. 

Please make changes, where the apps can set minimum width for a floor filter and also change the color of the floor filter to match other components in the app.

**Comment by mhdostal** [comment]
@mansibarodia10057 Thank you for the issue, they are both good ideas!
