### ISSUE TITLE
[Floor Filter Component] Floor filter does not work or can't select a facility if Sites layer is not present within the map.

### ISSUE THREAD

**Issue by mansibarodia10057** [Esri/arcgis-maps-sdk-swift-toolkit#263]
Sites layer is optional in Floor Manager. When Sites layer is missing in the map, Floor Filter just presents a blank Sites filter. 

There is no way to choose Facility and hence Floor Filter cannot be used further.

![Simulator Screen Shot - iPhone 14 - 2023-02-17 at 13 46 23](https://user-images.githubusercontent.com/49169550/219823171-5595c473-81e6-4d52-b28c-72d7b37ab723.png)

@dfeinzimer - FYI

**Comment by dfeinzimer** [comment]
Mansi provided me her repro data and I was able confirm a deficiency in the design that depends on the presence of a site in the floor manager data.
