### ISSUE TITLE
Utility Network - Only identify layers within the network

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#269]
When a location is tapped, the utility network tool will run an identify operation on all layers. Instead, it should only use layers that are within the utility network. This could potentially be a contributing factor to the behavior exhibited in #227.

Note: via the UN team, the best way to access the set of all layers in a utility network is network -> definition -> sources -> featureTable -> layer

Reported by @rolson

**Comment by rolson** [comment]
identify also has the potential to be very expensive if one of the layers is slow.  We see some base layers where the identify is painfully slow.  So excluding as many layers as possible is best.
