### ISSUE TITLE
[Floor Filter Component] Exposing sites, facilities and levels read-only info. 

### ISSUE THREAD

**Issue by mansibarodia10057** [Esri/arcgis-maps-sdk-swift-toolkit#271]
Currently there is no way of getting sites, facilities and levels info from floor filter, especially the selected site, selected facility and selected level info. Consuming apps will need this info to keep a track of user's location if the app deals with location related functionality. 

Looking at the current floor filter toolkit code, looks like floor filter view model has all the selection details, but the properties are private. These details can be read-only when exposed.

Please allow access to the details of the sites, facilities and levels in the map especially selected site, selected facility and selected level since other details can also be obtained from floor manager. 

@dfeinzimer - FYI.

**Comment by dfeinzimer** [comment]
> Please allow access to the details of the sites, facilities and levels in the map especially selected site, selected facility and selected level since other details can also be obtained from floor manager.

Hi @mansibarodia10057. As you said, since the sites, facilities, and levels are accessible through the floor manager and the floor manager is needed to initialize the tool itself, it seems that providing access to these properties would be redundant. Are you okay if we do not include this as apart of resolving this issue?

**Comment by mansibarodia10057** [comment]
> > Please allow access to the details of the sites, facilities and levels in the map especially selected site, selected facility and selected level since other details can also be obtained from floor manager.
> 
> Hi @mansibarodia10057. As you said, since the sites, facilities, and levels are accessible through the floor manager and the floor manager is needed to initialize the tool itself, it seems that providing access to these properties would be redundant. Are you okay if we do not include this as apart of resolving this issue?

@dfeinzimer - Yes access to all sites, facilities and levels via floor filter can be skipped. Mainly need access to selected level, facility, site. Selected vertical order would be required as well, but can access it from selected level object.

**Comment by dfeinzimer** [comment]
> @dfeinzimer - Yes access to all sites, facilities and levels via floor filter can be skipped. Mainly need access to selected level, facility, site. Selected vertical order would be required as well, but can access it from selected level object.

Great, thank you. Happy to report this is in progress now.
