### ISSUE TITLE
Need a way to programmatically set the selected site, facility, level

### ISSUE THREAD

**Issue by yo1995** [Esri/arcgis-maps-sdk-swift-toolkit#273]
The Indoors location data source needs to be able to set the selected site/floor/level when the user moves through/around a building.

The goal is to keep the floor filter component synchronized with the Indoors positioning system.

From Morakat and the indoors location team at the DevSummit.

Morakat added `setSite`, `setFacility`, and `setFloor` to the model, which works for him. The code is in his fork.

**Comment by yo1995** [comment]
cc: @dfeinzimer @mhdostal

**Comment by mhdostal** [comment]
Related to #271
