### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by swiatrzyk** [Esri/arcgis-maps-sdk-swift-toolkit#317]
I'd like to have possibility to use old API (v100) and the newest one (v200), so I can plan migrating extending it over time. Currently I cannot import both Swift Packages, as namings are conflicting

<img width="1093" alt="Screenshot 2023-04-20 at 12 12 19" src="https://user-images.githubusercontent.com/28967717/233336224-23df3fc1-fa11-400b-97b6-a6164d3e7e0f.png">

**Comment by mhdostal** [comment]
@swiatrzyk Thank you for your question. Unfortunately, the Toolkit 100.x and 200.x version were not designed to be used at the same time. The same goes for the ArcGIS Maps SDK for Swift (v200.x) and the original Runtime SDK for iOS (v100.15)

So you will need to upgrade to the new Swift API (v200.1) and the new Swift Toolkit. You can copy components from the v100.x Toolkit into your project, but you will have to update them to work with the new Swift API.

**Comment by dfeinzimer** [comment]
Hi @swiatrzyk I'll go ahead and close this question out due to inactivity. If you have any further questions feel free to open another issue or create a post in our [community forum](https://community.esri.com/t5/swift-maps-sdk-questions/bd-p/swift-maps-sdk-questions). Thanks!
