### ISSUE TITLE
Cannot build for Mac Catalyst with minimum Xcode version

### ISSUE THREAD

**Issue by philium** [Esri/arcgis-maps-sdk-swift-toolkit#318]
The README states that the minimum Xcode version is 14.0:

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/92bf62fb45b50070d69e9db1921e73d7a77a9bf6/README.md?plain=1#L27

However, the toolkit library cannot be built for Mac Catalyst using Xcode 14.0. There is a single build error:

![image](https://user-images.githubusercontent.com/2257493/233728935-d2f8cddc-f667-4bdf-8814-8a4bffaa0196.png)

The reason is because in the macOS 12.3 SDK (which Xcode 14.0 comes with), the `hidesBackButton` parameter of the `navigationBarBackButtonHidden` modifier does not have a default value:

![image](https://user-images.githubusercontent.com/2257493/233730702-291fd851-4750-4812-9740-273098d66cb2.png)

**Comment by mhdostal** [comment]
@philium Thank you!

When using Xcode 14, the workaround is to pass `true` to the modifier:
`.navigationBarBackButtonHidden(true)`

**Comment by mhdostal** [comment]
Note: this should be fixed if v200.2 does NOT bump the minimum Xcode version.
