### ISSUE TITLE
"v" prefix in semantic version tags possibly breaking SPM version resolution

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#336]
@zkline101 has noticed that SPM seems to have difficulty resolving package versions. 

He indicated the tag's "v" prefixes as a potential cause and there are similar discussions online around this issue.

Note that the SDK itself does not use a "v" prefix.

[See also](https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845/4)

It's not 100% that the "v" is the issue but it seems probable.

| Toolkit | SDK  |
|---|---|
| <img width="157" alt="Screenshot 2023-05-19 at 09 56 48" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/63ac8c86-8282-4a75-a133-9de0856d5be3"> | <img width="179" alt="Screenshot 2023-05-19 at 09 58 30" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/3b00af68-f766-4320-949b-3d49c1d5be62">  |

**Comment by yo1995** [comment]
https://github.com/apple/swift-package-manager/issues/5780 SPM has a [helper method](https://github.com/apple/swift-package-manager/blob/main/Sources/Basics/Version%2BExtensions.swift) to handle this, though I agree it is better to follow the standard semantic versioning pattern.

**Comment by zkline101** [comment]
Yeah, that is helpful so you can enter the version number in SPM without adding the "v". But the downside I think of including the prefixed "v" in the tag number is the version numbers aren't auto-filled out in SPM:
<img width="442" alt="Screenshot 2023-05-19 at 11 22 34 AM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/74069582/50715f64-2e41-4cc0-aa0b-5b07b72605e5">

And this is what is looks like when adding the SDK:
<img width="456" alt="Screenshot 2023-05-19 at 11 22 47 AM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/74069582/58bfc01b-99ca-4220-9573-cb04edf76c0d">

**Comment by mhdostal** [comment]
I've added this to the 200.2 project

**Comment by mhdostal** [comment]
This has been done for the 200.2.0 release.

**Comment by zkline101** [comment]
Thank you!
