### ISSUE TITLE
Add social preview image to the repo

### ISSUE THREAD

**Issue by mhdostal** [Esri/arcgis-maps-sdk-swift-toolkit#340]
Like the unreal engine samples: https://github.com/topics/arcgis-maps-sdk or https://github.com/topics/maps so it has more visual importance in the list of GitHub Topics

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/settings

There is an identical issue in the [Samples](https://github.com/Esri/arcgis-maps-sdk-swift-samples/issues/103) repo.

**Comment by dfeinzimer** [comment]
[Added!](https://github.com/topics/arcgis-maps-sdk#:~:text=arcgis%2Dmaps%2Dsdk%2Dswift%2Dtoolkit)

**Comment by mhdostal** [comment]
Looks great!
