### ISSUE TITLE
Clustering av Markers

### ISSUE THREAD

**Issue by jorgenstorlie** [Esri/arcgis-maps-sdk-swift-toolkit#343]
We want Clustering av Markers
https://developers.google.com/maps/documentation/ios-sdk/utility/marker-clustering

https://blog.kulman.sk/clustering-annotations-in-mkpampview/

Can this be added?

**Comment by nixta** [comment]
Hi, thanks for the feedback.

This functionality is on the roadmap, and we hope to have something released by the end of the year.

Please note that this is really functionality for the SDK itself, and not for the toolkit. A good place to suggest things like that is the [Native SDKs Ideas community](https://community.esri.com/t5/arcgis-maps-sdks-native-ideas/idb-p/arcgis-runtime-sdks-ideas). I'd recommend searching for an existing suggestion to upvote.

**Comment by dfeinzimer** [comment]
Hi @jorgenstorlie I'm happy to report that clustering was added within the SDK via [`ClusteringFeatureReduction`](https://developers.arcgis.com/swift/api-reference/documentation/arcgis/clusteringfeaturereduction) in August 2023. If you have any further questions feel free to create another issue, or create a post in our [community forum](https://community.esri.com/t5/swift-maps-sdk-questions/bd-p/swift-maps-sdk-questions) or in the Ideas community Nicholas mentioned above. Thanks!
