### ISSUE TITLE
Scalebar not working properly

### ISSUE THREAD

**Issue by mmoosbac94** [Esri/arcgis-maps-sdk-swift-toolkit#344]
Hi guys,

we are currently evaluating the Scalebar from Toolkit. It doesn't seem to be working as expected. First we get the exception "Generic parameter 'V' could not be inferred" when we try to use Scalebar in a view component. Even in the example the same error occurs. When we wrap it with a group, defining the generic parameter with "Scalebar" the exception disappears. But if we do it like in the example that we do not initialize the states like "spatialReference" and "unitsPerPoint", the Scalebar is not shown. If we initialize these states with wgs84 for spatialReference and any value for unitPerPoint the Scalebar appears. When we then change our viewpoint, the Scalebar is going to be updated, but with very incorrect values. You know about this issue?

Best regards
Marvin

**Comment by dfeinzimer** [comment]
Hi Marvin, 

Happy to help you get this figured out. The scalebar relies on the spatial reference, and a current units per point and viewpoint value to compute the correct distance. Passing in any value to `unitsPerPoint` will lead to incorrect values. The correct value for units per point can be obtained by using the `onUnitsPerPointChanged` modifier on a map view. I can try to give a more detailed suggestion if you're able to post a small snippet of your usage code here.

David

**Comment by mmoosbac94** [comment]
Hi David, thank you for your quick reply. I was able to solve the issue. I seems to be a Swift-UI Issue. I tried to work with a viewmodel and @Published values for the scalar properties. But this leads to incorrect scalebar values. When I do the same with @State like in the example it's working properly. Thanks again!
