### ISSUE TITLE
Examples App Name

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#379]
Have we ever given consideration to renaming the Examples app to "Toolkit Examples"? The app is indistinguishable from the SDK's examples app in the home screen.

Current:
<img width="235" alt="Screenshot 2023-07-28 at 15 25 10" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/650397b2-d3a8-4edc-9c48-325fcde087b6">

Proposed:
<img width="251" alt="Screenshot 2023-07-28 at 15 38 41" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/52de4e7f-d375-4797-b94d-b9e7910cd48d">

**Comment by mhdostal** [comment]
The Samples app simply uses _Samples_.

![image](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/3998072/91b4301d-c162-424f-a5a7-c8e65f299ac5)

Not sure that would be appropriate for the Toolkit, as they are _Toolkit Examples_, but maybe it would be OK.

What do the other platforms (.NET, QT, Android/Kotlin) do?

**Comment by dfeinzimer** [comment]
- .NET is using `ArcGIS Maps SDK for .NET Toolkit ([Platform])`
- QT is using `C++ Quick Toolkit Demo App`
- Android/Kotlin's plan is to use micro apps (e.g. for Forms they're using `FeatureFormsApp`).

I think this would mainly be a small quality of life improvement for those of us who have both the SDK and Toolkit examples app loaded on devices and simulators.

**Comment by nixta** [comment]
Toolkit Examples seems good to me.

Does it have the same icon as the Samples app?

**Comment by dfeinzimer** [comment]
> Does it have the same icon as the Samples app?

No - the "Samples" app that goes in App Store uses the white gear on purple background icon.

The SDK and Toolkit however both have their own examples app, both using the same display name ("Examples") and both have no icon making it hard to differentiate between the two.

**Comment by nixta** [comment]
Yeah. That's the Runtime/Native SDKs logo. I think we could add that to the Toolkit's Example project since a) we won't be putting it into the App Store, b) it's already part of the Samples project and c) it would help differentiate it when a user builds and runs it.

Thoughts?

**Comment by mhdostal** [comment]
I like "Toolkit Examples" and the Samples logo.

**Comment by dfeinzimer** [comment]
@yo1995 and @rolson, curious if either of you have thoughts on this? The name change I'd like to see.. the logo I'm a bit more indifferent on since it'd be using the same logo as Samples.

**Comment by yo1995** [comment]
Toolkit Examples 👍

**Comment by nixta** [comment]
> the logo I'm a bit more indifferent on since it'd be using the same logo as Samples

If we were releasing in the App Store, it would definitely need a different icon. AFAIK that's not on any roadmap.

Here's my thinking. If a developer has both samples and toolkit examples repos on their machine and building them to their device, the common icon works as it's saying "Cool, a Maps SDK project from Esri on my device. One is called Samples, the other Toolkit Examples. Nice.".

This absolutely does NOT need to be addressed here and now ☺️. The name is the key issue. But an icon does help make the project feel less incomplete and more of a 1st class component of the SDK, would also help distinguish it from the SDK's example app, and is a quick thing to update. ¯\_(ツ)_/¯

**Comment by dfeinzimer** [comment]
The logo plus rename addition has been merged. Thank you all for the input!
