### ISSUE TITLE
Fix `@Sendable` warnings when building tests

### ISSUE THREAD

**Issue by mhdostal** [Esri/arcgis-maps-sdk-swift-toolkit#402]
![image](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/3998072/8591df01-0cea-4d2d-adbc-4a33bce8d8a8)

**Comment by dfeinzimer** [comment]
@mhdostal, okay to close this? Appears outdated as of 200.6.0 / Xcode 16

<img width="698" alt="Screenshot 2024-11-25 at 10 38 14 AM" src="https://github.com/user-attachments/assets/282dcb36-dd9b-4e33-ae00-21dd5d947e73">
