### ISSUE TITLE
Localized string constants are stored when they should be computed

### ISSUE THREAD

**Issue by philium** [Esri/arcgis-maps-sdk-swift-toolkit#527]
Because a localized string is based on a locale and the locale can change while the app is running, localized string "constants" should be computed, not stored. In some places, like [this extension](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/db50212bb66caf94cf47e8f9f5ccb4643c553779/Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift#L791), the localized strings are stored as static properties, meaning that they won't change if that app's locale were to change. All static localized strings should be converted from stored to computed.

**Comment by mhdostal** [comment]
@philium Thanks for noticing that!!
