### ISSUE TITLE
Fix `DisclosureGroup` trailing padding on iOS

### ISSUE THREAD

**Issue by des12437** [Esri/arcgis-maps-sdk-swift-toolkit#528]
The disclosure groups in a Popup from the `Popup` example need more trailing padding since they look partially covered on iOS. Mac Catalyst does not have this issue since the disclosure group arrow icon is left rather than right aligned.

iPad Air:
<img width="278" alt="Screenshot 2023-12-01 at 10 45 56 AM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/117859673/1739f3e2-d05f-4eec-b4a9-6eb39152b121">

iPhone 14 Pro Max iOS 16:
<img src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/117859673/7e9816dc-3286-4d05-85e4-63a7bf6b41df" width="300">

**Comment by dfeinzimer** [comment]
* Note: The scroll bar can obscure the arrows at times.
