### ISSUE TITLE
200.4.0 package resolution failure

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#678]
There've been several reports of an issue with resolving the 200.4 package due to Git LFS:

```
Couldn't check out revision
'a01f570fc225c2ada99913c3430cc42b948075f0':
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
```

**Comment by philium** [comment]
> Adding symlink to LFS for Xcode

That seems unreasonable for us to expect customers to do, given that Git LFS is only used for testing.

**Comment by dfeinzimer** [comment]
> That seems unreasonable for us to expect customers to do

Agreed and (thankfully?) it seems likely that fix was a false positive. From what I've heard from others and after more of my own testing the failure seems intermittent, with and without the symlink in place.

**Comment by dfeinzimer** [comment]
Seemingly related issue at https://github.com/apple/swift-package-manager/issues/5351. Discussion on Swift Forums [here](https://forums.swift.org/t/swiftpm-with-git-lfs/42396/1).

We might need to rethink including LFS for the time being. 🫤

**Comment by dfeinzimer** [comment]
I've prepared branch `df/remove-lfs` if we proceed with a patch. Samples is able to checkout this branch without issue.

**Comment by dfeinzimer** [comment]
A patch has been issued and the release has been re-published and re-tagged. 

For anyone experiencing further issues please, the following files should be removed:
```
~/Library/Caches/org.swift.swiftpm
~/Library/org.swift.swiftpm
```
