### ISSUE TITLE
API Key documentation needed

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#716]
As of June '24 personal API keys are needed in order to use ArcGIS Location Services.

Provide further documentation/instruction.

cc @maryharvey 

Related: native-apis-doc/5776

**Comment by dfeinzimer** [comment]
@mhdostal, @maryharvey any changes we need to make Toolkit side?

**Comment by maryharvey** [comment]
@dfeinzimer Please refer to https://devtopia.esri.com/runtime/cocoa/issues/11263 and https://devtopia.esri.com/runtime/swift/issues/5514

**Comment by maryharvey** [comment]
@dfeinzimer Please refer to the cocoa and swift repos for details.

**Comment by dfeinzimer** [comment]
> @dfeinzimer Please refer to the cocoa and swift repos for details.

Noted, thanks!

**Comment by dfeinzimer** [comment]
Completed with #772
