### ISSUE TITLE
Xcode 16 warnings

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#777]
Triage and resolve 13 new warnings raised in Xcode 16

<img width="1012" alt="Screenshot 2024-06-25 at 6 28 58 PM" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/16397058/72d67d7a-e901-41a9-b464-8774947a6c61">

**Comment by rolson** [comment]
We have warnings in Xcode 15.4 that need to be fixed as well:
<img width="400" alt="image" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/3718875/c8237fee-51ab-4ce2-8e78-ede6722aa3dd">
Some of these will go away by getting the latest ArcGIS, but others have been there for a while and need to be fixed.
