### ISSUE TITLE
FloorFilter: SiteAndFacility Manager appearing when panning map

### ISSUE THREAD

**Issue by bastianmorath** [Esri/arcgis-maps-sdk-swift-toolkit#783]
When I add a FloorFilter to my map, then open and close the SiteAndFacilitySelector, then the SiteAndFacilitySelector shows again every time the map is panned (see video)

This can be fixed by not using a .constant binding as shown in the following screenshot. 

Also, as a sidenote, you do not need to pass the $isSitesAndFacilitiesHidden to all the subviews in order to dismiss the sheet. You can use a   '@Environment(\.dismiss) private var dismiss' in the corresponding views, which simplifies the code a little bit.

https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/5672716/220d1447-0d45-417b-b178-3f3b286ea37d

<img width="781" alt="image" src="https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/assets/5672716/fd1b26f3-f4db-477e-b42c-5d63df1d1fe4">

**Comment by mhdostal** [comment]
@bastianmorath - Thank you for the issue, especially the detailed explanation; that helps a lot!

**Comment by dfeinzimer** [comment]
Hi @bastianmorath, thank you for the bug report!

Can you please confirm which version of the toolkit you're using? Whether it's 200.4.0 or earlier?

**Comment by bastianmorath** [comment]
Hi @dfeinzimer, I've been using the newest version, 200.4.0.

**Comment by dfeinzimer** [comment]
@bastianmorath a PR has been merged for this issue and the issue should be fixed in the upcoming 200.5 release.

Thank you again for the report!

**Comment by dfeinzimer** [comment]
Hi @bastianmorath, the fix is available in 200.5.0 as of today.

**Comment by bastianmorath** [comment]
Awesome, thank you!
