### ISSUE TITLE
Xcode 16 build errors

### ISSUE THREAD

**Issue by dfeinzimer** [Esri/arcgis-maps-sdk-swift-toolkit#787]
Using Xcode 16.0 Beta 2 with pre-built binaries targeting an iOS simulator.

These appear to be related to `Sendable` changes as these attribute dictionaries have changed from `[String : Any]` to `[String : any Sendable]`.

### 1. 
> Undefined symbols for architecture arm64: "dispatch thunk of ArcGIS.GeoElement.attributes.getter : [Swift.String : Any]", referenced from: ... ArcGISToolkit.UtilityNetworkTrace.(startingPointDetail
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/654eb230b2e195de010d7e8987712457c338f925/Sources/ArcGISToolkit/Components/UtilityNetworkTrace/UtilityNetworkTrace.swift#L579

### 2. 
> Undefined symbols for architecture arm64:  "dispatch thunk of ArcGIS.Feature.attributes.getter : [Swift.String : Any]", referenced from: ArcGIS.ArcGISFeature.globalID.getter
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/654eb230b2e195de010d7e8987712457c338f925/Sources/ArcGISToolkit/Extensions/ArcGIS/ArcGISFeature.swift#L23-L25

### 3.
> Undefined symbols for architecture arm64:  "ArcGIS.GeocodeResult.attributes.getter : [Swift.String : Any]", referenced from: ... ArcGISToolkit.SearchResult.init(geocodeResult: ArcGIS.GeocodeResult, searchSource: ArcGISToolkit.SearchSource
https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/654eb230b2e195de010d7e8987712457c338f925/Sources/ArcGISToolkit/Components/Search/SearchResult.swift#L92-L101

**Comment by dfeinzimer** [comment]
Build errors are still present as of Beta 4.

Feedback FB14459597 submitted.

**Comment by dfeinzimer** [comment]
The issue does not appear to be limited to the Toolkit at this time.

Closing in deference to swift/5740 to centralize the discussion.

**Comment by sandeeps7** [comment]
Hi @dfeinzimer , any updates on this issue. I recently upgraded to Xcode 16 and facing this exact issue. Any help would be greatly appreciated. Thanks!

LOG:

```
Undefined symbols for architecture arm64:
  "dispatch thunk of ArcGIS.Feature.attributes.getter : [Swift.String : Any]", referenced from:
      (extension in ArcGISToolkit):ArcGIS.ArcGISFeature.globalID.getter : Foundation.UUID? in ArcGISToolkit.o
      (extension in ArcGISToolkit):ArcGIS.ArcGISFeature.globalID.getter : Foundation.UUID? in ArcGISToolkit.o
  "ArcGIS.Graphic.__allocating_init(geometry: ArcGIS.Geometry?, attributes: [Swift.String : Any], symbol: ArcGIS.Symbol?) -> ArcGIS.Graphic", referenced from:
      ArcGISToolkit.OverviewMap.(DataModel in _28865E661272E407DAB7FDFAE6449FDE).init() -> ArcGISToolkit.OverviewMap.(DataModel in _28865E661272E407DAB7FDFAE6449FDE) in ArcGISToolkit.o
      ArcGISToolkit.SearchResult.init(geocodeResult: ArcGIS.GeocodeResult, searchSource: ArcGISToolkit.SearchSource) -> ArcGISToolkit.SearchResult in ArcGISToolkit.o
      (1) suspend resume partial function for ArcGISToolkit.UtilityNetworkTraceViewModel.processAndAdd(startingPoint: ArcGISToolkit.UtilityNetworkTraceStartingPoint) async -> () in ArcGISToolkit.o
      (3) suspend resume partial function for ArcGISToolkit.UtilityNetworkTraceViewModel.processAndAdd(startingPoint: ArcGISToolkit.UtilityNetworkTraceStartingPoint) async -> () in ArcGISToolkit.o
      (4) suspend resume partial function for ArcGISToolkit.UtilityNetworkTraceViewModel.processAndAdd(startingPoint: ArcGISToolkit.UtilityNetworkTraceStartingPoint) async -> () in ArcGISToolkit.o
      closure #2 (ArcGIS.Geometry, ArcGIS.SimpleLineSymbol.Style, SwiftUI.Color) -> ArcGIS.Graphic in ArcGISToolkit.UtilityNetworkTraceViewModel.trace() async -> Swift.Bool in ArcGISToolkit.o
ld: symbol(s) not found for architecture arm64
```

**Comment by dfeinzimer** [comment]
Hi Sandeep, yes, we're actively working on fix and intend to release a patch shortly. 

Please follow [this thread](https://community.esri.com/t5/arcgis-maps-sdks-native-blog/xcode-16-compatibility-issue-with-arcgis-maps-sdk/ba-p/1539094/jump-to/first-unread-message) for up to date information.

**Comment by sandeeps7** [comment]
> Hi @sandeeps7, yes, we're actively working on a fix and intend to release a patch shortly.
> 
> Please follow [this thread](https://community.esri.com/t5/arcgis-maps-sdks-native-blog/xcode-16-compatibility-issue-with-arcgis-maps-sdk/ba-p/1539094/jump-to/first-unread-message) for up to date information.

Thank you David! this helps

**Comment by dfeinzimer** [comment]
[Version 200.5.1](https://github.com/Esri/arcgis-maps-sdk-swift/releases/tag/200.5.1) has been released which resolves the Xcode 16 build errors.

**Comment by sandeeps7** [comment]
Thanks David
