### ISSUE TITLE
OverviewMap does not change when switching basemaps on the original map

### ISSUE THREAD

**Issue by rolson** [Esri/arcgis-maps-sdk-swift-toolkit#858]
The OverviewMap control is great. I have noticed, however, that if you switch basemaps, the overview map component doesn't also switch. Should it?

<img width="721" alt="image" src="https://github.com/user-attachments/assets/16afbd77-d349-440e-b783-39d8c53f0206">

**Comment by dfeinzimer** [comment]
I believe for this you'd use the optional `map` parameter on [`forMapView(with:visibleArea:map:)`](https://developers.arcgis.com/swift/toolkit-api-reference/documentation/arcgistoolkit/overviewmap/formapview(with:visiblearea:map:)) or [`forSceneView(with:map:)`](https://developers.arcgis.com/swift/toolkit-api-reference/documentation/arcgistoolkit/overviewmap/forsceneview(with:map:)).

**Comment by philium** [comment]
We are currently using `arcGISTopographicBase` for the basemap style. For the case where the user hasn't provided their own map, we could switch to using a style with a dark equivalent and then automatically switch between the two.

**Comment by dfeinzimer** [comment]
> For the case where the user hasn't provided their own map, we could switch to using a style with a dark equivalent and then automatically switch between the two.

@philium Wouldn't the component then need a method of tracking the current primary basemap?

**Comment by philium** [comment]
No. We would just need to know what the current mode is (light/dark), which we could get from SwiftUI.

**Comment by rolson** [comment]
Sorry, the map I tested this with was topo, and so I thought that overview map used the same as the regular map (I'm not sure how I thought that was happening technically, magic?). Closing since the behavior I was asking for was based on a misunderstanding of the intention of this component.
