### ISSUE TITLE
PopupView fields visibility is ignored

### ISSUE THREAD

**Issue by des12437** [Esri/arcgis-maps-sdk-swift-toolkit#863]
The `PopupView` `FieldsPopupElement` does not display fields as configured on ArcGIS Online. All popupElement values are displayed using [`popupElement.labels` and `popupElement.formattedValues`](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/blob/main/Sources/ArcGISToolkit/Components/Popups/FieldsPopupElementView.swift#L24). `popupElement.fields` is not used to populate the popup which means fields with the `isVisible = false` condition is ignored so the field is shown in the popup. 

This results in inconsistencies between popups defined on ArcGIS Online and how they are displayed using the `PopupView` as reported  by a user on esri community. This inconsistency could be fixed at the toolkit or api level.

**Comment by mhdostal** [comment]
Here is the GeoNet issue: https://community.esri.com/t5/swift-maps-sdk-questions/issue-with-popups-in-arcgis-swift-sdk-200-x-for/m-p/1529362#M372

**Comment by dg0yal** [comment]
This is likely a bug in our logic to upgrade from the old popup spec to the new one internally

**Comment by dfeinzimer** [comment]
Ref Apollo 906

@mhdostal can this be closed?

**Comment by mhdostal** [comment]
I will verify that it is fixed.
