### ISSUE TITLE
Improve display text for trace results

### ISSUE THREAD

**Issue by dg0yal** [Esri/arcgis-maps-sdk-swift-toolkit#918]
Currently it just shows a number in the drop down - 
Would be better to display "2 Results" instead of the just "2" 
<img width="372" alt="image" src="https://github.com/user-attachments/assets/3e14a23a-3c13-49e4-a5f6-88a74c53f0e7">

**Comment by dfeinzimer** [comment]
Added in #979 

cc @dg0yal
