### ISSUE TITLE
`FloorFilter` - Remove automatically setting the viewpoint

### ISSUE THREAD

**Issue by kieranraftery** [Esri/arcgis-maps-sdk-swift-toolkit#936]
If there is exactly one site in a floor aware map, then the Floor Filter automatically sets the viewpoint to that site after the map loads. We would like this to be removed or give us the ability to disable this functionality.

**Comment by dfeinzimer** [comment]
Hi @kieranraftery, I'm happy to report this has been implemented and will be available in the upcoming 200.7 release via the `FloorFilter.automaticSingleSiteSelectionDisabled(_:)` modifier.
