### ISSUE TITLE
When using a RTL language the compass tool icon is messed up

### ISSUE THREAD

**Issue by kieranraftery** [Esri/arcgis-maps-sdk-swift-toolkit#948]
While testing with the device set to Arabic, we noticed that the icon in the compass tool appears wrong.

![Simulator Screenshot - iPhone 14 - 2024-10-30 at 18 35 14](https://github.com/user-attachments/assets/414fc33b-2175-47e6-bc7e-8c5cba149452)

**Comment by dfeinzimer** [comment]
Hi @kieranraftery, thank you for reporting this. This will be fixed in the upcoming 200.6 release.
